### ISSUE TITLE
Add readme and Dockerfile

### ISSUE THREAD

**Issue by jonbruner** [philkuz/PixelRNN#3]
Having a very clear step-by-step readme is the best way to ensure that readers run your notebook. The readme should explain dependencies (including TensorFlow) and indicate how best to install them. You're welcome to [borrow from this readme that I wrote](https://github.com/Steven-Hewitt/Entailment-with-Tensorflow/blob/master/README.md), for instance.

Also, having a Dockerfile ready to go is really helpful. The TensorFlow team has provided [a canonical Dockerfile](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker); you can basically just grab that and add in any additional dependencies you need, [as Steven has done here](https://github.com/Steven-Hewitt/Entailment-with-Tensorflow/blob/master/dockerfile).

**Comment by noahgolmant** [comment]
Just added a readme and dockerfile based (very heavily) on the one you referenced!
