### ISSUE TITLE
How long does it take you to train this?

### ISSUE THREAD

**Issue by jonbruner** [philkuz/PixelRNN#4]
I've got a really fast GPU, and each iteration takes about 40 seconds, at which rate it would take 40 days to train over 100,000 iterations! Have I made some change that's messed this up?

If this does actually take more than an hour or two to train, we should provide a pre-trained model for people to play with.

**Comment by noahgolmant** [comment]
Sorry, we left the default number of training epochs at 100k, but it really only takes 20 epochs or so to converge to a decent solution. We had originally been running it as a script and checking the progress periodically. Will push a change to that number soon.
