### ISSUE TITLE
Add narrative to Jupyter notebook

### ISSUE THREAD

**Issue by jonbruner** [philkuz/PixelRNN#5]
You're probably waiting for us to finish editing your Google Doc, but eventually we'll want some of the narrative from your main article to appear in the Jupyter notebook. This will make it much easier for readers to follow your code without flipping back and forth to the article on oreilly.com. You don't have to transpose all of your text to the Jupyter notebook, but enough to explain what you're doing along with some higher-level context on PixelRNN would be helpful.

**Comment by noahgolmant** [comment]
Just added some of the narrative to pixelrnn.ipynb!
